### ISSUE TITLE
Hysteresis not working

### ISSUE THREAD

**Issue by ma-be** [balmli/no.almli.thermostat#6]
Hi,
it seems to me, the hysteresis setting is not working.
As soos as the temperature is below the thermostat targrt temp, then it “starts heating” regardless the hysteresis value. And vice versa.
I am attaching screenshots when hysteresis is set to 0.5.
Would you mind checking it?
Thanks,
M. 
![cad5d302-449c-4309-aa75-91d80b9d9b65](https://user-images.githubusercontent.com/11045804/51398988-293bf780-1b45-11e9-9914-15bb5dfb618b.png)
![b964a45f-79f3-403b-8d98-a91df19fc2ed](https://user-images.githubusercontent.com/11045804/51398989-29d48e00-1b45-11e9-831b-9cf304091806.png)

**Comment by balmli** [comment]
Hi,  

The user interface for the themostat (the first screen) is a part of the mobile app for Homey, and might be a bit misleading.

Take a look at det second screen, if you slide to the right:  The state will be "Yes" if the thermostat is heating, and "No" if it is not heating.

**Comment by balmli** [comment]
With a target of 21.0 and hysteresis of 0.5, the temp will vary between 20.5 and 21.5.

The state on the second screen (yes / no) will tell you if the thermostat is heating or not.

And the UI in the mobile app is nice, but a bit confusing, since it says "heating" if the target is higher than the temperature, and "cooling" if the target is lower than the temperature.

**Comment by ma-be** [comment]
Thank you for the explanation. Now I see and confirm your description.
